vars:
  stage: qa

import:
  - catalog/ecs
  - mixins/us-east-2

components:
  terraform:
    ecs:
      vars:
        environment: "qa"
        desired_count: 2
        task_definition: "arn:aws:ecs:us-east-2:905418244733:task-definition/ecs-task--user-micro:1"
        security_group_id: "sg-0a0307d15b1b96b37" 
        subnets:
          - "subnet-0b33f652915bb47c4"
          - "subnet-014e89ee346b76b2f"
        # container_name: "app-container"
        # container_port: 8081
        # vpc_id: "vpc-0879e7786645465cf"