version: "3.9"
services:
  nginx:
    container_name: custom_nginx
    build: 
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/  
