name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input parameter'
        required: false
        default: 'default_value'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value
        run: |
          echo "The input value is: ${{ github.event.inputs.example_input }}"
      
      - name: Print current date and time
        run: date