name: Publish package example
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Change directory to nestjs test project
        run: cd node/testing && pwd && ls -l
      - name: Install dependencies
        working-directory: node/testing
        run: |
          pnpm install --frozen-lockfile
      - name: Verify dependencies
        working-directory: node/testing
        run: |
          pnpm list
      - name: Run Build
        working-directory: node/testing
        run: |
          pnpm run build:client
      - name: Run Publish
        working-directory: node/testing
        run: |
          pnpm run publish:client
