# .github/workflows/atmos-apply.yml
name: Atmos Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust as needed

    - name: Install Atmos
      run: npm install -g atmos

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Adjust as needed

    - name: Atmos Apply
      uses: cloudposse/github-action-atmos-terraform-apply@v1
      with:
        path: './components/terraform'  # Path to your Terraform configuration
      env:
        TF_VAR_my_variable: ${{ secrets.TF_VAR_MY_VARIABLE }}  # Adjust as needed
