name: Atmos Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment (qa or prod)"
        required: true
        type: choice
        options:
          - qa
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Atmos Plan
        uses: cloudposse/github-action-atmos-terraform-plan@v2
        with:
          component: "ecs"
          stack: ${{ github.event.inputs.environment }}
          atmos-version: 1.81.0
          atmos-config-path: ./rootfs/usr/local/etc/atmos/
